#### 다음 파일은 C:\Users\newny\yolov5에서 실행되는 것을 기준으로 작성된 코드입니다.

## 모델 불러오기

In [2]:
# 객체 검출해보기
import torch
model = torch.hub.load('ultralytics/yolov5', 'custom', path='best.pt', force_reload=True)

Downloading: "https://github.com/ultralytics/yolov5/zipball/master" to C:\Users\newny/.cache\torch\hub\master.zip
YOLOv5  2023-10-26 Python-3.8.18 torch-2.1.0+cpu CPU

Fusing layers... 
Model summary: 157 layers, 7015519 parameters, 0 gradients, 15.8 GFLOPs
Adding AutoShape... 


## 이미지 불러오기

In [82]:
# 이미지 띄우기
import cv2

img = cv2.imread('images/cat (1).png')

cv2.imshow('cat vs dog', img)
cv2.waitKey(0)
cv2.destroyAllWindows()

## 이미지 예측하기

In [83]:
result = model(img)
result.xyxyn[0] # 찾은 객체 관련 값
# x1, y1, x2, y2, confidence, class

tensor([[0.48129, 0.14641, 0.89736, 0.64268, 0.85646, 0.00000],
        [0.02957, 0.12236, 0.47321, 0.72522, 0.79983, 0.00000]])

## tensor 배열 → numpy 배열

In [79]:
import numpy
detect = result.xyxyn[0].numpy() # tensor 배열 → numpy 배열
detect

array([[    0.13717,   0.0074514,     0.82942,     0.90451,     0.74865,           1]], dtype=float32)

## 픽셀값으로 변경

In [80]:
x1,y1,x2,y2 = detect[0,0], detect[0,1], detect[0,2], detect[0,3]
img.shape
y_shape = img.shape[0]
x_shape = img.shape[1]
x1,y1,x2,y2 = map(int, (x1 * x_shape, y1 * y_shape, x2 * x_shape, y2 * y_shape)) # 픽셀값으로 변환
x1,y1,x2,y2

(126, 3, 764, 469)

## 객체 위치에 표현하기

In [81]:
cv2.rectangle(img, (x1,y1), (x2,y2), (0,0,255), 2)
cv2.imshow('cat vs dog', img)
cv2.waitKey(0)
cv2.destroyAllWindows()

## 2개 이상의 객체 탐지

In [99]:
## 이미지 띄우기
import cv2
import numpy
img = cv2.imread('images/cat (5).png')

result = model(img)
print(result.xyxyn[0]) # 찾은 객체 관련 값

detect = result.xyxyn[0].numpy() # tensor 배열 → numpy 배열
for i in range(len(detect)):
    x1,y1,x2,y2 = detect[i,0], detect[i,1], detect[i,2], detect[i,3]
    img.shape
    y_shape = img.shape[0]
    x_shape = img.shape[1]
    x1,y1,x2,y2 = map(int, (x1 * x_shape, y1 * y_shape, x2 * x_shape, y2 * y_shape)) # 픽셀값으로 변환
    x1,y1,x2,y2
    cv2.rectangle(img, (x1,y1), (x2,y2), (0,0,255), 2)
cv2.imshow('cat vs dog', img)
cv2.waitKey(0)
cv2.destroyAllWindows()

tensor([[0.70991, 0.00239, 0.90246, 0.44369, 0.85262, 0.00000],
        [0.52423, 0.05409, 0.68285, 0.49444, 0.83666, 0.00000],
        [0.12048, 0.10761, 0.30968, 0.53203, 0.82953, 0.00000],
        [0.33440, 0.00000, 0.49477, 0.40581, 0.79006, 0.00000]])


## 동영상에 적용

In [3]:
## 이미지 띄우기
import cv2
import numpy
cap = cv2.VideoCapture('images/dog_movie.mp4')

while cap.isOpened() :
    ret,img = cap.read()

    result = model(img)
    print(result.xyxyn[0]) # 찾은 객체 관련 값
    
    detect = result.xyxyn[0].numpy() # tensor 배열 → numpy 배열
    for i in range(len(detect)):
        x1,y1,x2,y2 = detect[i,0], detect[i,1], detect[i,2], detect[i,3]
        img.shape
        y_shape = img.shape[0]
        x_shape = img.shape[1]
        x1,y1,x2,y2 = map(int, (x1 * x_shape, y1 * y_shape, x2 * x_shape, y2 * y_shape)) # 픽셀값으로 변환
        cv2.rectangle(img, (x1,y1), (x2,y2), (0,0,255), 2)
        font = cv2.FONT_HERSHEY_SIMPLEX
        cv2.putText(img, str(detect[i,4]), (50, 50), font, 1, (255, 0, 0), 2, cv2.LINE_AA)

    if not ret:
        print('종료')
        break
            
    # 출력
    cv2.imshow('video', img)
        
    # 초당 30장 출력하고 키 입력 받음
    # 33/1000 초 딜레이
    key = cv2.waitKey(33)
        
    # 만약 1키를 눌렀다면 종료
    if key == 49 :
        print('종료')
        break
    
cap.release()
cv2.destroyAllWindows()

tensor([], size=(0, 6))
tensor([], size=(0, 6))
tensor([], size=(0, 6))
tensor([], size=(0, 6))
tensor([[0.00000, 0.23899, 0.13468, 0.72223, 0.26600, 1.00000]])
tensor([], size=(0, 6))
tensor([], size=(0, 6))
tensor([], size=(0, 6))
tensor([], size=(0, 6))
tensor([], size=(0, 6))
tensor([], size=(0, 6))
tensor([[0.00000, 0.18997, 0.56562, 0.89140, 0.30895, 1.00000]])
tensor([], size=(0, 6))
tensor([], size=(0, 6))
tensor([], size=(0, 6))
tensor([], size=(0, 6))
tensor([], size=(0, 6))
tensor([], size=(0, 6))
tensor([], size=(0, 6))
tensor([], size=(0, 6))
tensor([], size=(0, 6))
tensor([], size=(0, 6))
tensor([], size=(0, 6))
tensor([], size=(0, 6))
tensor([], size=(0, 6))
tensor([], size=(0, 6))
tensor([], size=(0, 6))
tensor([], size=(0, 6))
tensor([], size=(0, 6))
tensor([], size=(0, 6))
tensor([], size=(0, 6))
tensor([], size=(0, 6))
tensor([], size=(0, 6))
tensor([], size=(0, 6))
tensor([], size=(0, 6))
tensor([], size=(0, 6))
tensor([], size=(0, 6))
tensor([], size=(0, 6))
tensor